### PR TITLE
Pathopred

### PR DESCRIPTION
**Pull request by akvpr**
Adds a command for a docker version of pathopred for variant prediction.

### CODE REVIEW

**Comment by nanjiangshu** [comment]
Hi @akvpr, did you see my comments to your pull request?

**Comment by akvpr** [comment]
Do you mean the comments on the docker_pathopred repo? I can't see any other comments here yet, or maybe I'm looking in the wrong place?

**Comment by arneelof** [comment]
Jag vet inte riktigt......

**Comment by nanjiangshu** [comment]
@akvpr , comments to this pull request. That is your changes to the `run_job.py` for `pathopred` in the common backend. See above.

**Comment by arneelof** [comment]
Commit Summary

   - add docker pathopred command
   - fix formatting
   - change app dir

File Changes

   - *M* proj/pred/app/run_job.py
   <https://github.com/ElofssonLab/web_common_backend/pull/1/files#diff-0>
   (16)

Patch Links:

   - https://github.com/ElofssonLab/web_common_backend/pull/1.patch
   - https://github.com/ElofssonLab/web_common_backend/pull/1.diff


Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by akvpr** [comment]
Updated according to comments.

**Pull request merged**
